// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: debug.proto

package org.tensorflow.framework;

public final class DebugProtos {
  private DebugProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DebugTensorWatch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DebugTensorWatch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DebugOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DebugOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DebuggedSourceFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DebuggedSourceFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DebuggedSourceFiles_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DebuggedSourceFiles_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013debug.proto\022\ntensorflow\"\216\001\n\020DebugTenso" +
      "rWatch\022\021\n\tnode_name\030\001 \001(\t\022\023\n\013output_slot" +
      "\030\002 \001(\005\022\021\n\tdebug_ops\030\003 \003(\t\022\022\n\ndebug_urls\030" +
      "\004 \003(\t\022+\n#tolerate_debug_op_creation_fail" +
      "ures\030\005 \001(\010\"\201\001\n\014DebugOptions\022=\n\027debug_ten" +
      "sor_watch_opts\030\004 \003(\0132\034.tensorflow.DebugT" +
      "ensorWatch\022\023\n\013global_step\030\n \001(\003\022\035\n\025reset" +
      "_disk_byte_usage\030\013 \001(\010\"j\n\022DebuggedSource" +
      "File\022\014\n\004host\030\001 \001(\t\022\021\n\tfile_path\030\002 \001(\t\022\025\n" +
      "\rlast_modified\030\003 \001(\003\022\r\n\005bytes\030\004 \001(\003\022\r\n\005l" +
      "ines\030\005 \003(\t\"K\n\023DebuggedSourceFiles\0224\n\014sou" +
      "rce_files\030\001 \003(\0132\036.tensorflow.DebuggedSou" +
      "rceFileBj\n\030org.tensorflow.frameworkB\013Deb" +
      "ugProtosP\001Z<github.com/tensorflow/tensor" +
      "flow/tensorflow/go/core/protobuf\370\001\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tensorflow_DebugTensorWatch_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_DebugTensorWatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DebugTensorWatch_descriptor,
        new java.lang.String[] { "NodeName", "OutputSlot", "DebugOps", "DebugUrls", "TolerateDebugOpCreationFailures", });
    internal_static_tensorflow_DebugOptions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_DebugOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DebugOptions_descriptor,
        new java.lang.String[] { "DebugTensorWatchOpts", "GlobalStep", "ResetDiskByteUsage", });
    internal_static_tensorflow_DebuggedSourceFile_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_DebuggedSourceFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DebuggedSourceFile_descriptor,
        new java.lang.String[] { "Host", "FilePath", "LastModified", "Bytes", "Lines", });
    internal_static_tensorflow_DebuggedSourceFiles_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_DebuggedSourceFiles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DebuggedSourceFiles_descriptor,
        new java.lang.String[] { "SourceFiles", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
