// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node_def.proto

package org.tensorflow.framework;

public final class NodeProto {
  private NodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_NodeDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_NodeDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_NodeDef_AttrEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_NodeDef_AttrEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_NodeDef_ExperimentalDebugInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_NodeDef_ExperimentalDebugInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016node_def.proto\022\ntensorflow\032\020attr_value" +
      ".proto\"\265\002\n\007NodeDef\022\014\n\004name\030\001 \001(\t\022\n\n\002op\030\002" +
      " \001(\t\022\r\n\005input\030\003 \003(\t\022\016\n\006device\030\004 \001(\t\022+\n\004a" +
      "ttr\030\005 \003(\0132\035.tensorflow.NodeDef.AttrEntry" +
      "\022J\n\027experimental_debug_info\030\006 \001(\0132).tens" +
      "orflow.NodeDef.ExperimentalDebugInfo\032B\n\t" +
      "AttrEntry\022\013\n\003key\030\001 \001(\t\022$\n\005value\030\002 \001(\0132\025." +
      "tensorflow.AttrValue:\0028\001\0324\n\025Experimental" +
      "DebugInfo\022\033\n\023original_node_names\030\001 \003(\tBi" +
      "\n\030org.tensorflow.frameworkB\tNodeProtoP\001Z" +
      "=github.com/tensorflow/tensorflow/tensor" +
      "flow/go/core/framework\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.AttrValueProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_NodeDef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_NodeDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_NodeDef_descriptor,
        new java.lang.String[] { "Name", "Op", "Input", "Device", "Attr", "ExperimentalDebugInfo", });
    internal_static_tensorflow_NodeDef_AttrEntry_descriptor =
      internal_static_tensorflow_NodeDef_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_NodeDef_AttrEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_NodeDef_AttrEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_tensorflow_NodeDef_ExperimentalDebugInfo_descriptor =
      internal_static_tensorflow_NodeDef_descriptor.getNestedTypes().get(1);
    internal_static_tensorflow_NodeDef_ExperimentalDebugInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_NodeDef_ExperimentalDebugInfo_descriptor,
        new java.lang.String[] { "OriginalNodeNames", });
    org.tensorflow.framework.AttrValueProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
