// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue_runner.proto

package org.tensorflow.framework;

public final class QueueRunnerProtos {
  private QueueRunnerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_QueueRunnerDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_QueueRunnerDef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022queue_runner.proto\022\ntensorflow\032\021error_" +
      "codes.proto\"\252\001\n\016QueueRunnerDef\022\022\n\nqueue_" +
      "name\030\001 \001(\t\022\027\n\017enqueue_op_name\030\002 \003(\t\022\025\n\rc" +
      "lose_op_name\030\003 \001(\t\022\026\n\016cancel_op_name\030\004 \001" +
      "(\t\022<\n\034queue_closed_exception_types\030\005 \003(\016" +
      "2\026.tensorflow.error.CodeBp\n\030org.tensorfl" +
      "ow.frameworkB\021QueueRunnerProtosP\001Z<githu" +
      "b.com/tensorflow/tensorflow/tensorflow/g" +
      "o/core/protobuf\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.ErrorCodesProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_QueueRunnerDef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_QueueRunnerDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_QueueRunnerDef_descriptor,
        new java.lang.String[] { "QueueName", "EnqueueOpName", "CloseOpName", "CancelOpName", "QueueClosedExceptionTypes", });
    org.tensorflow.framework.ErrorCodesProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
