// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: saved_model.proto

package org.tensorflow.framework;

public final class SavedModelProtos {
  private SavedModelProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SavedModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SavedModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021saved_model.proto\022\ntensorflow\032\020meta_gr" +
      "aph.proto\"_\n\nSavedModel\022\"\n\032saved_model_s" +
      "chema_version\030\001 \001(\003\022-\n\013meta_graphs\030\002 \003(\013" +
      "2\030.tensorflow.MetaGraphDefBo\n\030org.tensor" +
      "flow.frameworkB\020SavedModelProtosP\001Z<gith" +
      "ub.com/tensorflow/tensorflow/tensorflow/" +
      "go/core/protobuf\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.MetaGraphProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_SavedModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_SavedModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SavedModel_descriptor,
        new java.lang.String[] { "SavedModelSchemaVersion", "MetaGraphs", });
    org.tensorflow.framework.MetaGraphProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
