// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: step_stats.proto

package org.tensorflow.framework;

public final class StepStatsProtos {
  private StepStatsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_AllocationRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_AllocationRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_AllocatorMemoryUsed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_AllocatorMemoryUsed_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_NodeOutput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_NodeOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_MemoryStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_MemoryStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_NodeExecStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_NodeExecStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeviceStepStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeviceStepStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_StepStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_StepStats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020step_stats.proto\022\ntensorflow\032\034allocati" +
      "on_description.proto\032\030tensor_description" +
      ".proto\"=\n\020AllocationRecord\022\024\n\014alloc_micr" +
      "os\030\001 \001(\003\022\023\n\013alloc_bytes\030\002 \001(\003\"\304\001\n\023Alloca" +
      "torMemoryUsed\022\026\n\016allocator_name\030\001 \001(\t\022\023\n" +
      "\013total_bytes\030\002 \001(\003\022\022\n\npeak_bytes\030\003 \001(\003\022\022" +
      "\n\nlive_bytes\030\004 \001(\003\0228\n\022allocation_records" +
      "\030\006 \003(\0132\034.tensorflow.AllocationRecord\022\036\n\026" +
      "allocator_bytes_in_use\030\005 \001(\003\"U\n\nNodeOutp" +
      "ut\022\014\n\004slot\030\001 \001(\005\0229\n\022tensor_description\030\003" +
      " \001(\0132\035.tensorflow.TensorDescription\"\354\001\n\013" +
      "MemoryStats\022\030\n\020temp_memory_size\030\001 \001(\003\022\036\n" +
      "\026persistent_memory_size\030\003 \001(\003\022#\n\033persist" +
      "ent_tensor_alloc_ids\030\005 \003(\003\022#\n\027device_tem" +
      "p_memory_size\030\002 \001(\003B\002\030\001\022)\n\035device_persis" +
      "tent_memory_size\030\004 \001(\003B\002\030\001\022.\n\"device_per" +
      "sistent_tensor_alloc_ids\030\006 \003(\003B\002\030\001\"\236\004\n\rN" +
      "odeExecStats\022\021\n\tnode_name\030\001 \001(\t\022\030\n\020all_s" +
      "tart_micros\030\002 \001(\003\022\033\n\023op_start_rel_micros" +
      "\030\003 \001(\003\022\031\n\021op_end_rel_micros\030\004 \001(\003\022\032\n\022all" +
      "_end_rel_micros\030\005 \001(\003\022/\n\006memory\030\006 \003(\0132\037." +
      "tensorflow.AllocatorMemoryUsed\022&\n\006output" +
      "\030\007 \003(\0132\026.tensorflow.NodeOutput\022\026\n\016timeli" +
      "ne_label\030\010 \001(\t\022\030\n\020scheduled_micros\030\t \001(\003" +
      "\022\021\n\tthread_id\030\n \001(\r\022<\n\021referenced_tensor" +
      "\030\013 \003(\0132!.tensorflow.AllocationDescriptio" +
      "n\022-\n\014memory_stats\030\014 \001(\0132\027.tensorflow.Mem" +
      "oryStats\022\027\n\017all_start_nanos\030\r \001(\003\022\032\n\022op_" +
      "start_rel_nanos\030\016 \001(\003\022\030\n\020op_end_rel_nano" +
      "s\030\017 \001(\003\022\031\n\021all_end_rel_nanos\030\020 \001(\003\022\027\n\017sc" +
      "heduled_nanos\030\021 \001(\003\"P\n\017DeviceStepStats\022\016" +
      "\n\006device\030\001 \001(\t\022-\n\nnode_stats\030\002 \003(\0132\031.ten" +
      "sorflow.NodeExecStats\";\n\tStepStats\022.\n\tde" +
      "v_stats\030\001 \003(\0132\033.tensorflow.DeviceStepSta" +
      "tsBo\n\030org.tensorflow.frameworkB\017StepStat" +
      "sProtosP\001Z=github.com/tensorflow/tensorf" +
      "low/tensorflow/go/core/framework\370\001\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.AllocationDescriptionProtos.getDescriptor(),
          org.tensorflow.framework.TensorDescriptionProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_AllocationRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_AllocationRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_AllocationRecord_descriptor,
        new java.lang.String[] { "AllocMicros", "AllocBytes", });
    internal_static_tensorflow_AllocatorMemoryUsed_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_AllocatorMemoryUsed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_AllocatorMemoryUsed_descriptor,
        new java.lang.String[] { "AllocatorName", "TotalBytes", "PeakBytes", "LiveBytes", "AllocationRecords", "AllocatorBytesInUse", });
    internal_static_tensorflow_NodeOutput_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_NodeOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_NodeOutput_descriptor,
        new java.lang.String[] { "Slot", "TensorDescription", });
    internal_static_tensorflow_MemoryStats_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_MemoryStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_MemoryStats_descriptor,
        new java.lang.String[] { "TempMemorySize", "PersistentMemorySize", "PersistentTensorAllocIds", "DeviceTempMemorySize", "DevicePersistentMemorySize", "DevicePersistentTensorAllocIds", });
    internal_static_tensorflow_NodeExecStats_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tensorflow_NodeExecStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_NodeExecStats_descriptor,
        new java.lang.String[] { "NodeName", "AllStartMicros", "OpStartRelMicros", "OpEndRelMicros", "AllEndRelMicros", "Memory", "Output", "TimelineLabel", "ScheduledMicros", "ThreadId", "ReferencedTensor", "MemoryStats", "AllStartNanos", "OpStartRelNanos", "OpEndRelNanos", "AllEndRelNanos", "ScheduledNanos", });
    internal_static_tensorflow_DeviceStepStats_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tensorflow_DeviceStepStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeviceStepStats_descriptor,
        new java.lang.String[] { "Device", "NodeStats", });
    internal_static_tensorflow_StepStats_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tensorflow_StepStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_StepStats_descriptor,
        new java.lang.String[] { "DevStats", });
    org.tensorflow.framework.AllocationDescriptionProtos.getDescriptor();
    org.tensorflow.framework.TensorDescriptionProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
