// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface CleanupGraphResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.CleanupGraphResponse)
    com.google.protobuf.MessageOrBuilder {
}
