// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package org.tensorflow.distruntime;

public interface CloseSessionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.CloseSessionResponse)
    com.google.protobuf.MessageOrBuilder {
}
