// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface CompleteInstanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.CompleteInstanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 instance_key = 1;</code>
   */
  int getInstanceKey();

  /**
   * <code>int32 source_rank = 2;</code>
   */
  int getSourceRank();
}
