// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface TracingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.TracingResponse)
    com.google.protobuf.MessageOrBuilder {
}
