// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public final class WorkerProtos {
  private WorkerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CreateWorkerSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CreateWorkerSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CreateWorkerSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CreateWorkerSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeleteWorkerSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeleteWorkerSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeleteWorkerSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeleteWorkerSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RegisterGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RegisterGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RegisterGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RegisterGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeregisterGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeregisterGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeregisterGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeregisterGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ExecutorOpts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ExecutorOpts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RunGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RunGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RunGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RunGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RecvTensorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RecvTensorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RecvTensorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RecvTensorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_LoggingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_LoggingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_LabeledStepStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_LabeledStepStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_LoggingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_LoggingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TraceOpts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TraceOpts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TracingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TracingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TracingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TracingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RecvBufRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RecvBufRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RecvBufResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RecvBufResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CompleteGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CompleteGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CompleteGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CompleteGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CompleteInstanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CompleteInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CompleteInstanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CompleteInstanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetStepSequenceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetStepSequenceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_StepSequence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_StepSequence_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetStepSequenceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetStepSequenceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014worker.proto\022\ntensorflow\032\031google/proto" +
      "buf/any.proto\032\020cost_graph.proto\032\020step_st" +
      "ats.proto\032\027device_attributes.proto\032\013grap" +
      "h.proto\032\014tensor.proto\032\022tensor_shape.prot" +
      "o\032\013types.proto\032\021error_codes.proto\032\014confi" +
      "g.proto\032\013debug.proto\032\022named_tensor.proto" +
      "\032\027tensorflow_server.proto\"\022\n\020GetStatusRe" +
      "quest\"L\n\021GetStatusResponse\0227\n\021device_att" +
      "ributes\030\001 \003(\0132\034.tensorflow.DeviceAttribu" +
      "tes\"~\n\032CreateWorkerSessionRequest\022\026\n\016ses" +
      "sion_handle\030\001 \001(\t\022)\n\nserver_def\030\002 \001(\0132\025." +
      "tensorflow.ServerDef\022\035\n\025isolate_session_" +
      "state\030\003 \001(\010\"\035\n\033CreateWorkerSessionRespon" +
      "se\"4\n\032DeleteWorkerSessionRequest\022\026\n\016sess" +
      "ion_handle\030\001 \001(\t\"\035\n\033DeleteWorkerSessionR" +
      "esponse\"\233\002\n\024RegisterGraphRequest\022\026\n\016sess" +
      "ion_handle\030\001 \001(\t\022$\n\034create_worker_sessio" +
      "n_called\030\006 \001(\010\022\'\n\tgraph_def\030\002 \001(\0132\024.tens" +
      "orflow.GraphDef\022\034\n\020has_control_flow\030\003 \001(" +
      "\010B\002\030\001\022/\n\rgraph_options\030\004 \001(\0132\030.tensorflo" +
      "w.GraphOptions\022/\n\rdebug_options\030\005 \001(\0132\030." +
      "tensorflow.DebugOptions\022\034\n\024collective_gr" +
      "aph_key\030\007 \001(\003\"-\n\025RegisterGraphResponse\022\024" +
      "\n\014graph_handle\030\001 \001(\t\"l\n\026DeregisterGraphR" +
      "equest\022\026\n\016session_handle\030\002 \001(\t\022$\n\034create" +
      "_worker_session_called\030\003 \001(\010\022\024\n\014graph_ha" +
      "ndle\030\001 \001(\t\"\031\n\027DeregisterGraphResponse\"&\n" +
      "\021CleanupAllRequest\022\021\n\tcontainer\030\001 \003(\t\"\024\n" +
      "\022CleanupAllResponse\"\212\001\n\014ExecutorOpts\022\024\n\014" +
      "record_costs\030\001 \001(\010\022\027\n\017record_timeline\030\003 " +
      "\001(\010\022\037\n\027record_partition_graphs\030\004 \001(\010\022*\n\"" +
      "report_tensor_allocations_upon_oom\030\005 \001(\010" +
      "\"\271\002\n\017RunGraphRequest\022\026\n\016session_handle\030\010" +
      " \001(\t\022$\n\034create_worker_session_called\030\n \001" +
      "(\010\022\024\n\014graph_handle\030\001 \001(\t\022\017\n\007step_id\030\002 \001(" +
      "\003\022+\n\texec_opts\030\005 \001(\0132\030.tensorflow.Execut" +
      "orOpts\022*\n\004send\030\003 \003(\0132\034.tensorflow.NamedT" +
      "ensorProto\022\020\n\010recv_key\030\004 \003(\t\022\022\n\nis_parti" +
      "al\030\006 \001(\010\022\033\n\023is_last_partial_run\030\007 \001(\010\022%\n" +
      "\035store_errors_in_response_body\030\t \001(\010\"\221\002\n" +
      "\020RunGraphResponse\022*\n\004recv\030\001 \003(\0132\034.tensor" +
      "flow.NamedTensorProto\022)\n\nstep_stats\030\002 \001(" +
      "\0132\025.tensorflow.StepStats\022,\n\ncost_graph\030\003" +
      " \001(\0132\030.tensorflow.CostGraphDef\022-\n\017partit" +
      "ion_graph\030\004 \003(\0132\024.tensorflow.GraphDef\022+\n" +
      "\013status_code\030\005 \001(\0162\026.tensorflow.error.Co" +
      "de\022\034\n\024status_error_message\030\006 \001(\t\"&\n\023Clea" +
      "nupGraphRequest\022\017\n\007step_id\030\001 \001(\003\"\026\n\024Clea" +
      "nupGraphResponse\"\373\001\n\021RecvTensorRequest\022\017" +
      "\n\007step_id\030\001 \001(\003\022\026\n\016rendezvous_key\030\002 \001(\t\022" +
      "\016\n\006dma_ok\030\003 \001(\010\0223\n\017client_locality\030\004 \001(\013" +
      "2\032.tensorflow.DeviceLocality\0223\n\017server_l" +
      "ocality\030\005 \001(\0132\032.tensorflow.DeviceLocalit" +
      "y\022/\n\021transport_options\030\006 \001(\0132\024.google.pr" +
      "otobuf.Any\022\022\n\nrequest_id\030\007 \001(\003\"\232\001\n\022RecvT" +
      "ensorResponse\022\'\n\006tensor\030\001 \001(\0132\027.tensorfl" +
      "ow.TensorProto\022\017\n\007is_dead\030\002 \001(\010\022\031\n\021send_" +
      "start_micros\030\003 \001(\003\022/\n\021transport_options\030" +
      "\004 \001(\0132\024.google.protobuf.Any\"o\n\016LoggingRe" +
      "quest\022\032\n\022enable_rpc_logging\030\001 \001(\010\022\033\n\023dis" +
      "able_rpc_logging\030\004 \001(\010\022\r\n\005clear\030\002 \001(\010\022\025\n" +
      "\rfetch_step_id\030\003 \003(\003\"N\n\020LabeledStepStats" +
      "\022\017\n\007step_id\030\001 \001(\003\022)\n\nstep_stats\030\002 \001(\0132\025." +
      "tensorflow.StepStats\"=\n\017LoggingResponse\022" +
      "*\n\004step\030\001 \003(\0132\034.tensorflow.LabeledStepSt" +
      "ats\"\253\001\n\tTraceOpts\022\020\n\010duration\030\001 \001(\001\022\031\n\021u" +
      "se_step_profiler\030\002 \001(\010\022\033\n\023use_kernel_pro" +
      "filer\030\003 \001(\010\022\035\n\025use_extended_profiler\030\004 \001" +
      "(\010\022\030\n\020use_gpu_profiler\030\005 \001(\010\022\033\n\023use_samp" +
      "le_profiler\030\006 \001(\010\"8\n\016TracingRequest\022&\n\007o" +
      "ptions\030\001 \001(\0132\025.tensorflow.TraceOpts\"\021\n\017T" +
      "racingResponse\"\270\002\n\016RecvBufRequest\022\017\n\007ste" +
      "p_id\030\001 \001(\003\022\032\n\022buf_rendezvous_key\030\002 \001(\t\022\021" +
      "\n\tnum_bytes\030\003 \001(\003\022\017\n\007buf_ptr\030\004 \001(\006\0223\n\017cl" +
      "ient_locality\030\005 \001(\0132\032.tensorflow.DeviceL" +
      "ocality\0223\n\017server_locality\030\006 \001(\0132\032.tenso" +
      "rflow.DeviceLocality\022/\n\021transport_option" +
      "s\030\007 \001(\0132\024.google.protobuf.Any\022\022\n\nsrc_dev" +
      "ice\030\010 \001(\t\022\022\n\ndst_device\030\t \001(\t\022\022\n\nrequest" +
      "_id\030\n \001(\003\"\222\001\n\017RecvBufResponse\022\017\n\007buf_ptr" +
      "\030\001 \001(\006\022\021\n\tnum_bytes\030\002 \001(\003\022\017\n\007is_dead\030\003 \001" +
      "(\010\022/\n\021transport_options\030\004 \001(\0132\024.google.p" +
      "rotobuf.Any\022\031\n\021send_start_micros\030\005 \001(\003\"g" +
      "\n\024CompleteGroupRequest\022\021\n\tgroup_key\030\001 \001(" +
      "\005\022\022\n\ngroup_size\030\002 \001(\005\022\023\n\013device_type\030\003 \001" +
      "(\t\022\023\n\013device_name\030\004 \003(\t\"\216\001\n\025CompleteGrou" +
      "pResponse\022\021\n\tgroup_key\030\001 \001(\005\022\022\n\ngroup_si" +
      "ze\030\002 \001(\005\022\023\n\013device_type\030\003 \001(\t\022\021\n\tnum_tas" +
      "ks\030\004 \001(\005\022\023\n\013device_name\030\005 \003(\t\022\021\n\ttask_na" +
      "me\030\006 \003(\t\"\227\002\n\027CompleteInstanceRequest\022\014\n\004" +
      "name\030\001 \001(\t\022\014\n\004type\030\002 \001(\005\022\'\n\tdata_type\030\003 " +
      "\001(\0162\024.tensorflow.DataType\022+\n\005shape\030\004 \001(\013" +
      "2\034.tensorflow.TensorShapeProto\022\021\n\tgroup_" +
      "key\030\005 \001(\005\022\022\n\ngroup_size\030\006 \001(\005\022\024\n\014instanc" +
      "e_key\030\007 \001(\005\022\023\n\013device_type\030\010 \001(\t\022\025\n\rsubd" +
      "iv_offset\030\t \003(\005\022\016\n\006device\030\n \001(\t\022\021\n\tis_so" +
      "urce\030\013 \001(\010\"E\n\030CompleteInstanceResponse\022\024" +
      "\n\014instance_key\030\001 \001(\005\022\023\n\013source_rank\030\002 \001(" +
      "\005\"+\n\026GetStepSequenceRequest\022\021\n\tgraph_key" +
      "\030\001 \003(\003\"7\n\014StepSequence\022\021\n\tgraph_key\030\001 \001(" +
      "\003\022\024\n\014next_step_id\030\002 \001(\003\"J\n\027GetStepSequen" +
      "ceResponse\022/\n\rstep_sequence\030\001 \003(\0132\030.tens" +
      "orflow.StepSequenceBm\n\032org.tensorflow.di" +
      "struntimeB\014WorkerProtosP\001Z<github.com/te" +
      "nsorflow/tensorflow/tensorflow/go/core/p" +
      "rotobuf\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          org.tensorflow.framework.CostGraphProtos.getDescriptor(),
          org.tensorflow.framework.StepStatsProtos.getDescriptor(),
          org.tensorflow.framework.DeviceAttributesProtos.getDescriptor(),
          org.tensorflow.framework.GraphProtos.getDescriptor(),
          org.tensorflow.framework.TensorProtos.getDescriptor(),
          org.tensorflow.framework.TensorShapeProtos.getDescriptor(),
          org.tensorflow.framework.TypesProtos.getDescriptor(),
          org.tensorflow.framework.ErrorCodesProtos.getDescriptor(),
          org.tensorflow.framework.ConfigProtos.getDescriptor(),
          org.tensorflow.framework.DebugProtos.getDescriptor(),
          org.tensorflow.framework.NamedTensorProtos.getDescriptor(),
          org.tensorflow.distruntime.ServerProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_GetStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_GetStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_GetStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_GetStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetStatusResponse_descriptor,
        new java.lang.String[] { "DeviceAttributes", });
    internal_static_tensorflow_CreateWorkerSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_CreateWorkerSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CreateWorkerSessionRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "ServerDef", "IsolateSessionState", });
    internal_static_tensorflow_CreateWorkerSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_CreateWorkerSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CreateWorkerSessionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_DeleteWorkerSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tensorflow_DeleteWorkerSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeleteWorkerSessionRequest_descriptor,
        new java.lang.String[] { "SessionHandle", });
    internal_static_tensorflow_DeleteWorkerSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tensorflow_DeleteWorkerSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeleteWorkerSessionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_RegisterGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tensorflow_RegisterGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RegisterGraphRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "CreateWorkerSessionCalled", "GraphDef", "HasControlFlow", "GraphOptions", "DebugOptions", "CollectiveGraphKey", });
    internal_static_tensorflow_RegisterGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tensorflow_RegisterGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RegisterGraphResponse_descriptor,
        new java.lang.String[] { "GraphHandle", });
    internal_static_tensorflow_DeregisterGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_tensorflow_DeregisterGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeregisterGraphRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "CreateWorkerSessionCalled", "GraphHandle", });
    internal_static_tensorflow_DeregisterGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_tensorflow_DeregisterGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeregisterGraphResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_CleanupAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_tensorflow_CleanupAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupAllRequest_descriptor,
        new java.lang.String[] { "Container", });
    internal_static_tensorflow_CleanupAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_tensorflow_CleanupAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupAllResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_ExecutorOpts_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_tensorflow_ExecutorOpts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ExecutorOpts_descriptor,
        new java.lang.String[] { "RecordCosts", "RecordTimeline", "RecordPartitionGraphs", "ReportTensorAllocationsUponOom", });
    internal_static_tensorflow_RunGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_tensorflow_RunGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RunGraphRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "CreateWorkerSessionCalled", "GraphHandle", "StepId", "ExecOpts", "Send", "RecvKey", "IsPartial", "IsLastPartialRun", "StoreErrorsInResponseBody", });
    internal_static_tensorflow_RunGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_tensorflow_RunGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RunGraphResponse_descriptor,
        new java.lang.String[] { "Recv", "StepStats", "CostGraph", "PartitionGraph", "StatusCode", "StatusErrorMessage", });
    internal_static_tensorflow_CleanupGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_tensorflow_CleanupGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupGraphRequest_descriptor,
        new java.lang.String[] { "StepId", });
    internal_static_tensorflow_CleanupGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_tensorflow_CleanupGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupGraphResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_RecvTensorRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_tensorflow_RecvTensorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RecvTensorRequest_descriptor,
        new java.lang.String[] { "StepId", "RendezvousKey", "DmaOk", "ClientLocality", "ServerLocality", "TransportOptions", "RequestId", });
    internal_static_tensorflow_RecvTensorResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_tensorflow_RecvTensorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RecvTensorResponse_descriptor,
        new java.lang.String[] { "Tensor", "IsDead", "SendStartMicros", "TransportOptions", });
    internal_static_tensorflow_LoggingRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_tensorflow_LoggingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_LoggingRequest_descriptor,
        new java.lang.String[] { "EnableRpcLogging", "DisableRpcLogging", "Clear", "FetchStepId", });
    internal_static_tensorflow_LabeledStepStats_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_tensorflow_LabeledStepStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_LabeledStepStats_descriptor,
        new java.lang.String[] { "StepId", "StepStats", });
    internal_static_tensorflow_LoggingResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_tensorflow_LoggingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_LoggingResponse_descriptor,
        new java.lang.String[] { "Step", });
    internal_static_tensorflow_TraceOpts_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_tensorflow_TraceOpts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TraceOpts_descriptor,
        new java.lang.String[] { "Duration", "UseStepProfiler", "UseKernelProfiler", "UseExtendedProfiler", "UseGpuProfiler", "UseSampleProfiler", });
    internal_static_tensorflow_TracingRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_tensorflow_TracingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TracingRequest_descriptor,
        new java.lang.String[] { "Options", });
    internal_static_tensorflow_TracingResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_tensorflow_TracingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TracingResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_RecvBufRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_tensorflow_RecvBufRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RecvBufRequest_descriptor,
        new java.lang.String[] { "StepId", "BufRendezvousKey", "NumBytes", "BufPtr", "ClientLocality", "ServerLocality", "TransportOptions", "SrcDevice", "DstDevice", "RequestId", });
    internal_static_tensorflow_RecvBufResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_tensorflow_RecvBufResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RecvBufResponse_descriptor,
        new java.lang.String[] { "BufPtr", "NumBytes", "IsDead", "TransportOptions", "SendStartMicros", });
    internal_static_tensorflow_CompleteGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_tensorflow_CompleteGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CompleteGroupRequest_descriptor,
        new java.lang.String[] { "GroupKey", "GroupSize", "DeviceType", "DeviceName", });
    internal_static_tensorflow_CompleteGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_tensorflow_CompleteGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CompleteGroupResponse_descriptor,
        new java.lang.String[] { "GroupKey", "GroupSize", "DeviceType", "NumTasks", "DeviceName", "TaskName", });
    internal_static_tensorflow_CompleteInstanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_tensorflow_CompleteInstanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CompleteInstanceRequest_descriptor,
        new java.lang.String[] { "Name", "Type", "DataType", "Shape", "GroupKey", "GroupSize", "InstanceKey", "DeviceType", "SubdivOffset", "Device", "IsSource", });
    internal_static_tensorflow_CompleteInstanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_tensorflow_CompleteInstanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CompleteInstanceResponse_descriptor,
        new java.lang.String[] { "InstanceKey", "SourceRank", });
    internal_static_tensorflow_GetStepSequenceRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_tensorflow_GetStepSequenceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetStepSequenceRequest_descriptor,
        new java.lang.String[] { "GraphKey", });
    internal_static_tensorflow_StepSequence_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_tensorflow_StepSequence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_StepSequence_descriptor,
        new java.lang.String[] { "GraphKey", "NextStepId", });
    internal_static_tensorflow_GetStepSequenceResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_tensorflow_GetStepSequenceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetStepSequenceResponse_descriptor,
        new java.lang.String[] { "StepSequence", });
    com.google.protobuf.AnyProto.getDescriptor();
    org.tensorflow.framework.CostGraphProtos.getDescriptor();
    org.tensorflow.framework.StepStatsProtos.getDescriptor();
    org.tensorflow.framework.DeviceAttributesProtos.getDescriptor();
    org.tensorflow.framework.GraphProtos.getDescriptor();
    org.tensorflow.framework.TensorProtos.getDescriptor();
    org.tensorflow.framework.TensorShapeProtos.getDescriptor();
    org.tensorflow.framework.TypesProtos.getDescriptor();
    org.tensorflow.framework.ErrorCodesProtos.getDescriptor();
    org.tensorflow.framework.ConfigProtos.getDescriptor();
    org.tensorflow.framework.DebugProtos.getDescriptor();
    org.tensorflow.framework.NamedTensorProtos.getDescriptor();
    org.tensorflow.distruntime.ServerProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
