// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: saved_tensor_slice.proto

package org.tensorflow.util;

public final class SavedTensorSliceProtos {
  private SavedTensorSliceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SavedSliceMeta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SavedSliceMeta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SavedTensorSliceMeta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SavedTensorSliceMeta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SavedSlice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SavedSlice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SavedTensorSlices_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SavedTensorSlices_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030saved_tensor_slice.proto\022\ntensorflow\032\022" +
      "tensor_shape.proto\032\022tensor_slice.proto\032\014" +
      "tensor.proto\032\013types.proto\032\016versions.prot" +
      "o\"\234\001\n\016SavedSliceMeta\022\014\n\004name\030\001 \001(\t\022+\n\005sh" +
      "ape\030\002 \001(\0132\034.tensorflow.TensorShapeProto\022" +
      "\"\n\004type\030\003 \001(\0162\024.tensorflow.DataType\022+\n\005s" +
      "lice\030\004 \003(\0132\034.tensorflow.TensorSliceProto" +
      "\"l\n\024SavedTensorSliceMeta\022*\n\006tensor\030\001 \003(\013" +
      "2\032.tensorflow.SavedSliceMeta\022(\n\010versions" +
      "\030\002 \001(\0132\026.tensorflow.VersionDef\"n\n\nSavedS" +
      "lice\022\014\n\004name\030\001 \001(\t\022+\n\005slice\030\002 \001(\0132\034.tens" +
      "orflow.TensorSliceProto\022%\n\004data\030\003 \001(\0132\027." +
      "tensorflow.TensorProto\"i\n\021SavedTensorSli" +
      "ces\022.\n\004meta\030\001 \001(\0132 .tensorflow.SavedTens" +
      "orSliceMeta\022$\n\004data\030\002 \001(\0132\026.tensorflow.S" +
      "avedSliceB2\n\023org.tensorflow.utilB\026SavedT" +
      "ensorSliceProtosP\001\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.TensorShapeProtos.getDescriptor(),
          org.tensorflow.framework.TensorSliceProtos.getDescriptor(),
          org.tensorflow.framework.TensorProtos.getDescriptor(),
          org.tensorflow.framework.TypesProtos.getDescriptor(),
          org.tensorflow.framework.VersionsProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_SavedSliceMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_SavedSliceMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SavedSliceMeta_descriptor,
        new java.lang.String[] { "Name", "Shape", "Type", "Slice", });
    internal_static_tensorflow_SavedTensorSliceMeta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_SavedTensorSliceMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SavedTensorSliceMeta_descriptor,
        new java.lang.String[] { "Tensor", "Versions", });
    internal_static_tensorflow_SavedSlice_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_SavedSlice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SavedSlice_descriptor,
        new java.lang.String[] { "Name", "Slice", "Data", });
    internal_static_tensorflow_SavedTensorSlices_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_SavedTensorSlices_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SavedTensorSlices_descriptor,
        new java.lang.String[] { "Meta", "Data", });
    org.tensorflow.framework.TensorShapeProtos.getDescriptor();
    org.tensorflow.framework.TensorSliceProtos.getDescriptor();
    org.tensorflow.framework.TensorProtos.getDescriptor();
    org.tensorflow.framework.TypesProtos.getDescriptor();
    org.tensorflow.framework.VersionsProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
