// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package org.tensorflow.util;

public interface WorkerHeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.WorkerHeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.WorkerShutdownMode shutdown_mode = 1;</code>
   */
  int getShutdownModeValue();
  /**
   * <code>.tensorflow.WorkerShutdownMode shutdown_mode = 1;</code>
   */
  org.tensorflow.util.WorkerShutdownMode getShutdownMode();

  /**
   * <code>.tensorflow.WatchdogConfig watchdog_config = 2;</code>
   */
  boolean hasWatchdogConfig();
  /**
   * <code>.tensorflow.WatchdogConfig watchdog_config = 2;</code>
   */
  org.tensorflow.util.WatchdogConfig getWatchdogConfig();
  /**
   * <code>.tensorflow.WatchdogConfig watchdog_config = 2;</code>
   */
  org.tensorflow.util.WatchdogConfigOrBuilder getWatchdogConfigOrBuilder();
}
