// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example_parser_configuration.proto

package org.tensorflow.example;

public final class ExampleParserConfigurationProtos {
  private ExampleParserConfigurationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_VarLenFeatureProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_VarLenFeatureProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_FixedLenFeatureProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_FixedLenFeatureProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_FeatureConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_FeatureConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ExampleParserConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ExampleParserConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"example_parser_configuration.proto\022\nte" +
      "nsorflow\032\022tensor_shape.proto\032\014tensor.pro" +
      "to\032\013types.proto\"\243\001\n\022VarLenFeatureProto\022#" +
      "\n\005dtype\030\001 \001(\0162\024.tensorflow.DataType\022!\n\031v" +
      "alues_output_tensor_name\030\002 \001(\t\022\"\n\032indice" +
      "s_output_tensor_name\030\003 \001(\t\022!\n\031shapes_out" +
      "put_tensor_name\030\004 \001(\t\"\273\001\n\024FixedLenFeatur" +
      "eProto\022#\n\005dtype\030\001 \001(\0162\024.tensorflow.DataT" +
      "ype\022+\n\005shape\030\002 \001(\0132\034.tensorflow.TensorSh" +
      "apeProto\022.\n\rdefault_value\030\003 \001(\0132\027.tensor" +
      "flow.TensorProto\022!\n\031values_output_tensor" +
      "_name\030\004 \001(\t\"\232\001\n\024FeatureConfiguration\022=\n\021" +
      "fixed_len_feature\030\001 \001(\0132 .tensorflow.Fix" +
      "edLenFeatureProtoH\000\0229\n\017var_len_feature\030\002" +
      " \001(\0132\036.tensorflow.VarLenFeatureProtoH\000B\010" +
      "\n\006config\"\276\001\n\032ExampleParserConfiguration\022" +
      "K\n\013feature_map\030\001 \003(\01326.tensorflow.Exampl" +
      "eParserConfiguration.FeatureMapEntry\032S\n\017" +
      "FeatureMapEntry\022\013\n\003key\030\001 \001(\t\022/\n\005value\030\002 " +
      "\001(\0132 .tensorflow.FeatureConfiguration:\0028" +
      "\001B|\n\026org.tensorflow.exampleB ExamplePars" +
      "erConfigurationProtosP\001Z;github.com/tens" +
      "orflow/tensorflow/tensorflow/go/core/exa" +
      "mple\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.TensorShapeProtos.getDescriptor(),
          org.tensorflow.framework.TensorProtos.getDescriptor(),
          org.tensorflow.framework.TypesProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_VarLenFeatureProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_VarLenFeatureProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_VarLenFeatureProto_descriptor,
        new java.lang.String[] { "Dtype", "ValuesOutputTensorName", "IndicesOutputTensorName", "ShapesOutputTensorName", });
    internal_static_tensorflow_FixedLenFeatureProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_FixedLenFeatureProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_FixedLenFeatureProto_descriptor,
        new java.lang.String[] { "Dtype", "Shape", "DefaultValue", "ValuesOutputTensorName", });
    internal_static_tensorflow_FeatureConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_FeatureConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_FeatureConfiguration_descriptor,
        new java.lang.String[] { "FixedLenFeature", "VarLenFeature", "Config", });
    internal_static_tensorflow_ExampleParserConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_ExampleParserConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ExampleParserConfiguration_descriptor,
        new java.lang.String[] { "FeatureMap", });
    internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_descriptor =
      internal_static_tensorflow_ExampleParserConfiguration_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    org.tensorflow.framework.TensorShapeProtos.getDescriptor();
    org.tensorflow.framework.TensorProtos.getDescriptor();
    org.tensorflow.framework.TypesProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
